[build]
publish     = "."
functions   = "netlify/functions"
environment = { SECRETS_SCAN_OMIT_PATHS = "node_modules/aws-sdk/**" }

[[redirects]]
from   = "/api/*"
to     = "/.netlify/functions/:splat"
status = 200

[functions]
node_bundler = "esbuild"
